# Generated by Django 3.0.1 on 2020-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='stream',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('Ragging', 'Ragging'), ('Administration', 'Administration'), ('Faculty', 'Faculty'), ('Hostel', 'Hostel')], max_length=20),
        ),
    ]
